"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import NavigationHeader from "@/components/Navbar";
import Header from "@/components/Header";
import { Footer } from "@/components/Footer";

import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const pathname = usePathname();
  const hideNavbarRoutes = ['/'];


  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header/>
        { !hideNavbarRoutes.includes(pathname) && <NavigationHeader /> }
        {children}
        <Footer/>
      </body>
    </html>
  );
}
